name: Calculate Bundle Size

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  calculate-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: 'yarn install'
          build_command: 'yarn build'
          dist_path: '/dist'
          token: ${{ secrets.GITHUB_TOKEN }}
